
Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.


  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.31.15.127:8501
  External URL: http://54.79.9.198:8501

2025-02-23 14:16:58.992 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 7, in <module>
    import pages as pg
  File "/home/ec2-user/soccer_boots_project/pages/__init__.py", line 2, in <module>
    from .find import show_Find
ModuleNotFoundError: No module named 'pages.find'
  Stopping...

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.


  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.31.15.127:8501
  External URL: http://54.79.9.198:8501

2025-02-23 14:59:24.768 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 7, in <module>
    import pages as pg
  File "/home/ec2-user/soccer_boots_project/pages/__init__.py", line 2, in <module>
    from .find import show_Find
ModuleNotFoundError: No module named 'pages.find'
2025-02-23 14:59:36.656 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/pages/home.py", line 2, in <module>
    import pages as pg
  File "/home/ec2-user/soccer_boots_project/pages/__init__.py", line 2, in <module>
    from .find import show_Find
ModuleNotFoundError: No module named 'pages.find'
2025-02-23 14:59:41.879 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 7, in <module>
    import pages as pg
  File "/home/ec2-user/soccer_boots_project/pages/__init__.py", line 2, in <module>
    from .find import show_Find
ModuleNotFoundError: No module named 'pages.find'
2025-02-23 15:24:40.286 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 145, in filter_page
    if st.session_state["sort_order"] == "가나다순":
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "sort_order". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 01:51:19.906 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 145, in filter_page
    if st.session_state["sort_order"] == "가나다순":
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "sort_order". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 04:30:06.241 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 145, in filter_page
    if st.session_state["sort_order"] == "가나다순":
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "sort_order". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 04:30:07.850 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 145, in filter_page
    if st.session_state["sort_order"] == "가나다순":
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "sort_order". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 04:30:11.201 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 145, in filter_page
    if st.session_state["sort_order"] == "가나다순":
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "sort_order". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 04:31:54.418 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 145, in filter_page
    if st.session_state["sort_order"] == "가나다순":
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "sort_order". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 04:34:34.256 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 145, in filter_page
    if st.session_state["sort_order"] == "가나다순":
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "sort_order". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 04:34:36.343 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 145, in filter_page
    if st.session_state["sort_order"] == "가나다순":
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "sort_order". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 04:34:38.765 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 145, in filter_page
    if st.session_state["sort_order"] == "가나다순":
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "sort_order". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 05:56:28.541 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 145, in filter_page
    if st.session_state["sort_order"] == "가나다순":
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "sort_order". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 05:56:36.777 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 145, in filter_page
    if st.session_state["sort_order"] == "가나다순":
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "sort_order". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 05:56:49.744 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 157, in filter_page
    current_page = min(st.session_state["page_number"], total_pages)  # 현재 페이지가 total_pages를 초과하지 않도록 보정
                       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "page_number". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 05:56:50.106 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 145, in filter_page
    if st.session_state["sort_order"] == "가나다순":
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "sort_order". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 05:56:50.471 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 157, in filter_page
    current_page = min(st.session_state["page_number"], total_pages)  # 현재 페이지가 total_pages를 초과하지 않도록 보정
                       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "page_number". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 05:56:51.636 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 157, in filter_page
    current_page = min(st.session_state["page_number"], total_pages)  # 현재 페이지가 total_pages를 초과하지 않도록 보정
                       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "page_number". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 05:56:53.443 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 157, in filter_page
    current_page = min(st.session_state["page_number"], total_pages)  # 현재 페이지가 total_pages를 초과하지 않도록 보정
                       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "page_number". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 05:56:54.392 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 157, in filter_page
    current_page = min(st.session_state["page_number"], total_pages)  # 현재 페이지가 total_pages를 초과하지 않도록 보정
                       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "page_number". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 05:56:55.594 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 157, in filter_page
    current_page = min(st.session_state["page_number"], total_pages)  # 현재 페이지가 total_pages를 초과하지 않도록 보정
                       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "page_number". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 05:56:56.155 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 157, in filter_page
    current_page = min(st.session_state["page_number"], total_pages)  # 현재 페이지가 total_pages를 초과하지 않도록 보정
                       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "page_number". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 05:56:56.939 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 157, in filter_page
    current_page = min(st.session_state["page_number"], total_pages)  # 현재 페이지가 total_pages를 초과하지 않도록 보정
                       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "page_number". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 05:56:57.676 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 157, in filter_page
    current_page = min(st.session_state["page_number"], total_pages)  # 현재 페이지가 total_pages를 초과하지 않도록 보정
                       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "page_number". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 05:57:21.660 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 157, in filter_page
    current_page = min(st.session_state["page_number"], total_pages)  # 현재 페이지가 total_pages를 초과하지 않도록 보정
                       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "page_number". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 06:00:46.347 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 145, in filter_page
    if st.session_state["sort_order"] == "가나다순":
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "sort_order". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 06:04:43.604 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 145, in filter_page
    if st.session_state["sort_order"] == "가나다순":
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "sort_order". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 06:04:47.589 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 157, in filter_page
    current_page = min(st.session_state["page_number"], total_pages)  # 현재 페이지가 total_pages를 초과하지 않도록 보정
                       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "page_number". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 06:05:21.353 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 145, in filter_page
    if st.session_state["sort_order"] == "가나다순":
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "sort_order". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 06:05:35.100 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 157, in filter_page
    current_page = min(st.session_state["page_number"], total_pages)  # 현재 페이지가 total_pages를 초과하지 않도록 보정
                       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "page_number". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 06:07:15.572 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 145, in filter_page
    if st.session_state["sort_order"] == "가나다순":
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "sort_order". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 06:07:18.427 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 145, in filter_page
    if st.session_state["sort_order"] == "가나다순":
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "sort_order". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 06:07:20.202 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 145, in filter_page
    if st.session_state["sort_order"] == "가나다순":
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "sort_order". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 06:15:38.704 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 145, in filter_page
    if st.session_state["sort_order"] == "가나다순":
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "sort_order". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 06:17:25.080 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 145, in filter_page
    if st.session_state["sort_order"] == "가나다순":
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "sort_order". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 06:17:31.824 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 145, in filter_page
    if st.session_state["sort_order"] == "가나다순":
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "sort_order". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 06:21:32.775 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 145, in filter_page
    if st.session_state["sort_order"] == "가나다순":
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "sort_order". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 06:21:41.098 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 145, in filter_page
    if st.session_state["sort_order"] == "가나다순":
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "sort_order". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
  Stopping...

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.


  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.31.15.127:8501
  External URL: http://54.79.9.198:8501

2025-02-24 06:29:29.623 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 145, in filter_page
    if st.session_state["sort_order"] == "가나다순":
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "sort_order". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 06:29:39.424 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 145, in filter_page
    if st.session_state["sort_order"] == "가나다순":
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "sort_order". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 06:29:41.921 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 145, in filter_page
    if st.session_state["sort_order"] == "가나다순":
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "sort_order". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 06:29:49.138 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 145, in filter_page
    if st.session_state["sort_order"] == "가나다순":
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "sort_order". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 06:29:58.329 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 145, in filter_page
    if st.session_state["sort_order"] == "가나다순":
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "sort_order". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 06:30:06.948 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 145, in filter_page
    if st.session_state["sort_order"] == "가나다순":
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "sort_order". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 06:30:07.921 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 145, in filter_page
    if st.session_state["sort_order"] == "가나다순":
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "sort_order". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 06:30:34.345 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 145, in filter_page
    if st.session_state["sort_order"] == "가나다순":
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "sort_order". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 06:30:37.591 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 145, in filter_page
    if st.session_state["sort_order"] == "가나다순":
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "sort_order". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 06:30:43.266 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 145, in filter_page
    if st.session_state["sort_order"] == "가나다순":
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "sort_order". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 06:33:07.109 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 145, in filter_page
    if st.session_state["sort_order"] == "가나다순":
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "sort_order". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 06:33:10.358 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 145, in filter_page
    if st.session_state["sort_order"] == "가나다순":
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "sort_order". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 06:39:27.677 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 145, in filter_page
    if st.session_state["sort_order"] == "가나다순":
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "sort_order". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 06:44:41.000 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 145, in filter_page
    if st.session_state["sort_order"] == "가나다순":
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "sort_order". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 06:44:44.057 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 145, in filter_page
    if st.session_state["sort_order"] == "가나다순":
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "sort_order". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 06:56:35.594 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 145, in filter_page
    if st.session_state["sort_order"] == "가나다순":
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "sort_order". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 07:03:50.144 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 145, in filter_page
    if st.session_state["sort_order"] == "가나다순":
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "sort_order". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 07:03:53.660 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 145, in filter_page
    if st.session_state["sort_order"] == "가나다순":
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "sort_order". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 07:03:55.602 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 145, in filter_page
    if st.session_state["sort_order"] == "가나다순":
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "sort_order". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 07:03:57.763 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 145, in filter_page
    if st.session_state["sort_order"] == "가나다순":
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "sort_order". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 07:04:01.400 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 145, in filter_page
    if st.session_state["sort_order"] == "가나다순":
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "sort_order". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 07:09:11.139 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 145, in filter_page
    if st.session_state["sort_order"] == "가나다순":
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "sort_order". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
  Stopping...

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.


  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.31.15.127:8501
  External URL: http://54.79.9.198:8501

2025-02-24 07:11:42.836 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 145, in filter_page
    if st.session_state["sort_order"] == "가나다순":
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "sort_order". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 07:11:46.389 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 145, in filter_page
    if st.session_state["sort_order"] == "가나다순":
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "sort_order". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 07:12:34.527 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 145, in filter_page
    if st.session_state["sort_order"] == "가나다순":
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "sort_order". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
2025-02-24 07:12:38.703 Uncaught app execution
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 452, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 497, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 121, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 591, in code_to_exec
    exec(code, module.__dict__)
  File "/home/ec2-user/soccer_boots_project/app.py", line 69, in <module>
    go_to()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 240, in show_Find
    filter_page()
  File "/home/ec2-user/soccer_boots_project/pages/find.py", line 145, in filter_page
    if st.session_state["sort_order"] == "가나다순":
       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state_proxy.py", line 101, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/safe_session_state.py", line 96, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/ec2-user/anaconda3/envs/soccer/lib/python3.12/site-packages/streamlit/runtime/state/session_state.py", line 454, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "sort_order". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
